name: Cross-Platform Build with PyInstaller

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

jobs:
  check-format:
    name: Check Formatting 🔍
    uses: ./.github/workflows/check-format.yaml
    permissions:
      contents: read

  build:
    needs: check-format
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            python-version: '3.11'
            target: linux
            runs-on: ubuntu-latest
          - os: windows-latest
            python-version: '3.11'
            target: windows
            runs-on: windows-latest

    runs-on: ${{ matrix.runs-on }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install tesserocr for Windows
        if: matrix.os == 'windows-latest'
        run: |
          Invoke-WebRequest -Uri https://github.com/simonflueckiger/tesserocr-windows_build/releases/download/tesserocr-v2.7.0-tesseract-5.3.4/tesserocr-2.7.0-cp311-cp311-win_amd64.whl -OutFile tesserocr-2.7.0-cp311-cp311-win_amd64.whl
          python -m pip install tesserocr-2.7.0-cp311-cp311-win_amd64.whl

      - name: Install PyInstaller for Windows
        if: matrix.os == 'windows-latest'
        run: python -m pip install pyinstaller==6.19.0

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Install Windows dependencies
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install -r requirements-win.txt

      - name: Write .env file Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          echo "LOCAL_RELEASE_TAG=${GITHUB_REF_NAME}" >> .env
          echo "LOCAL_RELEASE_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> .env

      - name: Write .env file Windows
        if: matrix.os == 'windows-latest'
        run: |
          @"
          LOCAL_RELEASE_TAG=$env:GITHUB_REF_NAME
          LOCAL_RELEASE_DATE=$(Get-Date -Format 'yyyy-MM-ddTHH:mm:ssZ')
          "@ | Out-File -FilePath .env -Encoding ASCII
        shell: pwsh

      - name: Build device enumeration module on Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd src/win32DeviceEnum
          python setup.py build_ext --inplace
          cd ../..

      - name: Build with PyInstaller (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          if ("${{ github.event_name }}" -eq "pull_request") {
            pyinstaller --clean --noconfirm scoresight.spec -- --win --debug
          } else {
            pyinstaller --clean --noconfirm scoresight.spec -- --win
          }

      - name: Build with PyInstaller (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --clean --noconfirm scoresight.spec

      - name: Add version to .iss file
        if: matrix.os == 'windows-latest'
        run: |
          $version = (Get-Content -Path scoresight.iss -Raw) -replace '@SCORESIGHT_VERSION@', $env:GITHUB_REF_NAME
          $version | Out-File -FilePath scoresight.iss -Encoding ASCII
        shell: pwsh

      - name: Compile .ISS to .EXE Installer
        if: matrix.os == 'windows-latest'
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
        with:
          path: scoresight.iss
          options: /O+

      - name: Create tar Linux
        if: matrix.os == 'ubuntu-latest'
        # strip the folder name from the tar
        run: |
          chmod a+x dist/scoresight
          tar -cvf scoresight.tar -C dist scoresight

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: scoresight-${{ matrix.target }}
          path: ${{ matrix.os == 'windows-latest' && 'dist/scoresight-setup.exe' || 'scoresight.tar' }}
